export const genres = [
  "action", "Action",
  "adventure", "Adventure",
  "animation", "Animation",
  "biography", "Biography",
  "comedy", "Comedy",
  "crime", "Crime",
  "documentary", "Documentary",
  "drama", "Drama",
  "family", "Family",
  "fantasy", "Fantasy",
  "film-noir", "Film-Noir",
  "history", "History",
  "horror", "Horror",
  "music", "Music",
  "musical", "Musical",
  "mystery", "Mystery",
  "romance", "Romance",
  "sci-fi", "Sci-Fi",
  "sport", "Sport",
  "thriller", "Thriller",
  "war", "War",
  "western", "Western"
];
